services:

  backend:
    build: ./backend
    ports:
      - "5000"
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build: ./interface
    ports:
      - "8001:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5